services:
  - type: web
    name: resume-matcher
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: python run_app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FLASK_ENV
        value: production

